server:
  port: 9086
  max-http-header-size: 100000
spring:
  datasource:
    dynamic:
      primary: control
      strict: false
      datasource:
        druid:
          max-wait: 10000
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:sqlserver://yhocn.cn;DatabaseName=yh_xinxicaiji
          username: sa
          password: Lyh07910_001
  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

